/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package dummy_app

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'dummy_app.greeting' plugin.
 */
class Dummy_appPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("dummy_app.greeting")

        then:
        project.tasks.findByName("greeting") != null
    }
}
